export const TODO_ACTIONS = {
  ADD_TODO: "ADD_TODO",
  TOGGLE_TODO: "TOGGLE_TODO",
  REMOVE_TODO: "REMOVE_TODO"
};

export const VISIBILITY_FILTER_ACTIONS = {
  SET_VISIBILITY_FILTER: "SET_VISIBILITY_FILTER"
};

export const VISIBILITY_STATE_ACTIONS = {
  SHOW_ALL: "SHOW_ALL",
  SHOW_COMPLETED: "SHOW_COMPLETED"
};
